### ISSUE TITLE
TypeScript Compiler Status

### ISSUE THREAD

**Issue by igormcoelho** [neo-one-suite/neo-one#1014]
HI! May I ask how is current TypeScript support? Is it currently 100% or does it need any further adaptations on NeoVM?
I believe this is a very important project, and we plan to integrate it to our Smart Account generator (https://neoresearch.io/smacco) which is currently using C# compiler, but it would be much better to generate (and compile)  Javascript.
Congratulations again, and count on us!
On behalf of NeoResearch community

**Comment by dicarlo2** [comment]
We still need further adaptations. I'm going to sync with Peter during DevCon to see what we can do.
