### ISSUE TITLE
Incorrect Parameter types should throw error.

### ISSUE THREAD

**Issue by davemneo** [neo-one-suite/neo-one#1047]
### Description

Editor not providing appropriate warnings for invalid parameter types.

### Steps to Reproduce

With a given interface defined in the MixIn 
```typescript
interface TransferOptions {
  from: Address;
  to: Address;
}
```
When the test attempts to call, with invalid value types:
```typescript
        const initTransferResult = await smartContract.transferContract(
          {
            from: publisher.userAccount.id,
            to: recipient.userAccount.id,
          },
          { from: masterAccountID.address },
        );
```
Note: No errors or warnings were provided to the developer

When this mix-in function is called with the invalid parameters supplied by the contract...
```typescript
    @constant
    public transferContract({ from, to }: TransferOptions) {
      if (Address.isCaller(from) && this.mutableOwner === from) {
        if (from === to) {    //  <<<  Error thrown here
          this.cancelTransfer();
        } else {
          this.initiateTransfer(to);
        }
[...]
```
Result during execution is this error:
```
    Error [INVOCATION_CALL]: Invalid PICKITEM Index: 1. Value: ["00"]
```

**Expected behavior:** there to be an obvious in-editor error that identifies invalid types being passed.  
correct parameter would have been: ```typescript publisher.userAccount.id.address```

**Actual behavior:** Runtime error is thrown.

**Reproduces how often:** 100%

**Comment by dicarlo2** [comment]
this works fine - just not when developing in `neo-one-smart-contract-lib`
