### ISSUE TITLE
Create template: Cannot read property 'on' of undefined error

### ISSUE THREAD

**Issue by NicoCurylo** [neo-one-suite/neo-one#108]
### Description

Creating a template throws a `Cannot read property 'on' of undefined` error

### Steps to Reproduce

1. Launch neo-one cli
2. Execute `create simulation app @neo-one/simulation-react`

**Expected behavior:** Finish the process

**Actual behavior:** Throws an error

**Reproduces how often:** 100%

### Versions

neo-one cli version `v1.0.0-alpha.44`

**Comment by dicarlo2** [comment]
Sorry about that, currently the simulations functionality is on hold until we finish up the TypeScript compiler, so it's unlikely to work (as you saw).

**Comment by NicoCurylo** [comment]
Okay, when do you expect a fix for this?
