### ISSUE TITLE
Smart contract deploying

### ISSUE THREAD

**Issue by nimmortal** [neo-one-suite/neo-one#1278]
Hello guys.
I have a question about smart contract deploying.
All information provided on webpage is awesome and well explained.
However there is missed info about smart contract deploy - https://neo-one.io/docs/deployment#Deploying-to-a-Public-Network

Could you please fill this section?
Currently this is a serious blocker for us to use neo-one in our game.

**Comment by afragapane** [comment]
We are working to get this done soon.  Getting neo-one compiled contracts deployed on the main network is one of our current top priorities.  Thanks for letting us know!  In the meantime we have full support for working with a private network.
