### ISSUE TITLE
Tutorial test environment

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#1339]
### Description
The tutorial uses create-react-app to setup the project.  By default, tests are not run in the node environment with create-react-app and you cannot override the config option for the test environment.  You can override the environment for specific files though.  We should add a note in the tutorial that you must add:
```
/**
 * @jest-environment node
 */
```
at the top of your neo-one tests for them to run properly.

**Comment by dicarlo2** [comment]
The tutorial includes this: https://neo-one.io/tutorial#Testing

@afragapane do we need to add this elsewhere in the docs?

**Comment by afragapane** [comment]
ah it does... i swear it didn't when I made this last week lol. And nah, just since we're using create-react-app there.
