### ISSUE TITLE
Tutorial final test

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#1341]
### Description
Tutorial uses `accountIDs[0]` to test mintTokens, but right now `accountIDs[0]` is loaded with 0 funds.  We should change this to be either `accountIDs[2+]` or use the master account.

**Comment by afragapane** [comment]
Might also be worth adding to the documentation somewhere exactly what the test wallets are.  How much NEO/GAS they have, their addresses, ect.

**Comment by dicarlo2** [comment]
Documentation has that information: https://neo-one.io/docs/testing

**Comment by afragapane** [comment]
cool, in that case we should just change the accountID tutorial uses and direct them to where they can find that information.

**Comment by danwbyrne** [comment]
Has this been handled? I'll add it to the website fixes issues. @afragapane
