### ISSUE TITLE
Refactor Renovate to batch dependency updates

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#1352]
### Description

Renovate is really annoying, especially recently. It would be nice if it could `batch` all of the dependency updates it wants to, even if it is one big fat failing PR it would be easier to fix. General workflow could be:
1. Renovate sees a dep needs update
2. Appends the dep update as either a commit or just make the change and tack it on. Shouldn't be hard to have ordered commits tho with all the info we want.
3. If something is *actually* broken, then remove it and force push the upgrades that work.
4. The kicked out upgrade will just be the first thing on the *next* batched PR.

This way we could just weekly go through and fix a bunch of actual problems, instead of staring at bors / praying the dep updates stop coming in.

Not actually sure how to implement this, but I can look at it eventually. If someone wants to pick it up sooner please by all means :)

**Comment by dicarlo2** [comment]
https://github.com/renovatebot/renovate/issues/1342

**Comment by dicarlo2** [comment]
https://renovatebot.com/docs/configuration-options/#packagerules is probably the easiest - just define a package rule which matches all dependencies and puts them in a group.
