### ISSUE TITLE
`yarn neo-one version` spazzes out

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#1379]
### Description

Starting up the server spazzes out (simplest repro is to use `yarn neo-one version`)

### Steps to Reproduce

1. `yarn neo-one reset --static-neo-one`
2. `yarn neo-one version`

**Expected behavior:** neo-one server cleanly starts and the cli cleanly reports it

**Actual behavior:** looks crazy broken

**Reproduces how often:** 100%

### Versions

v1.1.2

### Additional Information

Nada.

**Comment by danwbyrne** [comment]
closed in preference of #1431
