### ISSUE TITLE
Node sync is inconsistent/gets stuck.

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#1455]
### Description

Node occasionally gets stuck with no logs.

### Steps to Reproduce

1. Start a fresh node
2. ...
3. See that the sync gets stuck.

**Expected behavior:** Syncs all the way to the present.

**Actual behavior:** Gets stuck.

**Reproduces how often:** 100%

### Additional Information

This is almost certainly due to the blacklisting logic being wonky.

**Comment by danwbyrne** [comment]
After some investigation and additional logging it doesn't look like it is blacklisting every peer like I suspected originally. Instead it looks like after awhile it just *only* tries to connect to peers and doesn't receive any messages.

**Comment by danwbyrne** [comment]
Seeing as this can be fixed by using health probes described in #1614 we can probably close this. I'm going to open an issue for using them in docker-compose as well. @dicarlo2
