### ISSUE TITLE
Must add "neo-one" to "scripts" section of package.json with npm

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#1527]
### Description
`npm run neo-one init` does not work unless `neo-one` is added to the scripts section of the package.json.  Note `yarn neo-one init` works fine in either case. 

### Steps to Reproduce

1. npx create-react-app issuetest --typescript
2. cd issuetest
3. npm run neo-one init (observe failure)
4. Add "neo-one": 'neo-one' as a key: value to the "scripts" section of the package.json
5. npm run neo-one init (observe success)

### Versions
1.1.4

### Additional Information
Ideally, this should work without needing to add "neo-one" into "scripts".  If there is no way to achieve this, then we just need to update the documentation.

**Comment by spencercorwin** [comment]
You have to run `npx neo-one init` with `npm`. I'll update that Tutorial page and look for other places where we say to use `npm run <executable>`.
