### ISSUE TITLE
Fix flaky E2E tests

### ISSUE THREAD

**Issue by spencercorwin** [neo-one-suite/neo-one#1537]
# Description

`circleci` e2e tests and `bors` builds often fail when submitting PRs, requiring someone to rerun `bors`, thus delaying *vital* updates.

### Steps to Reproduce

1. Submit a PR
2. `bors r+`
3. Build may or may not fail
4. If it fails it may be due to flaky e2e tests
5. Rerun `bors r+`
6. `bors` succeeds and merges

**Expected behavior:** Build succeeds on first try (nearly) every time

**Actual behavior:** Fails sometimes

**Reproduces how often:** 25% of the time approx

### Versions

N/A

### Additional Information

None.

**Comment by danwbyrne** [comment]
I would start cataloging the different failures here. I think there are ~4-6 flaky tests.
