### ISSUE TITLE
CircleCI parallelism

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#1659]
I was taking a look at https://circleci.com/docs/2.0/parallelism-faster-jobs/

Could `parallelism: 2` in our e2e tests be causing more flakiness?

**Comment by dicarlo2** [comment]
@danwbyrne why would parallelism affect test flakiness?

**Comment by danwbyrne** [comment]
Port assignment between e2e tests running at the same time. With my e2e retry changes I don't think it will be an issue. It was just a thought while looking at CI configs with Spencer.

**Comment by dicarlo2** [comment]
Parallelism means they run on two different vms.
