### ISSUE TITLE
Add neo-one-node-bin e2e test

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#1685]
### Description

Should basically just write a configuration to a temporary directory, then start the node using that config and finally check that it's producing blocks. Private net with consensus enabled.

**Comment by danwbyrne** [comment]
Looking at `scripts/e2e/One.js` it seems `one.createExecAsync` is pretty tuned to cli projects specifically.

I'm going to just make my own commands and add them to one.cleanup(...) unless you want me to alter the One script but you just refactored it a lot so up to you.
