### ISSUE TITLE
Consider switching to Rush

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#1688]
### Description

Instead of lerna. 

https://rushjs.io/pages/intro/welcome/

**Comment by danwbyrne** [comment]
I think we should also consider using https://www.npmjs.com/package/@microsoft/package-deps-hash, rush has some helpers for it. If we got our build setup in a place where packages our built individually we could attach a `package-dep-hash` to it and then subsequent build calls could be skipped if `dist.package-dep === src.package-dep`.

This way we would never really need to delete our dist folder even between rebasing :)
