### ISSUE TITLE
build command not completing

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#1715]
### Description
`yarn neo-one build` is not completing.  It seems to get stuck on the "Setting up Wallets" step.

### Steps to Reproduce

e2e tests:
1.  yarn e2e build
2. Observe test does not complete, just sits there

website:
1. yarn website:start:dev-builds
2. yarn website:start:dev
3. Navigate to a course
4. Paste the solution and click "build"
5. Observe the command sits at "Setting up Wallets" indefinitely

**Expected behavior:** Build command succeeds

**Actual behavior:** Build command stops

**Reproduces how often:** 100%

### Versions
neo-one-cli v 1.3.0

**Comment by dicarlo2** [comment]
first issue should be fixed with https://github.com/neo-one-suite/neo-one/commit/23c27f7c7088dd2b76d41a7b446cf8893469b006
