### ISSUE TITLE
Update System Fee / Network Fee Calculations for Neo 2.x and Neo 3.0

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#1880]
https://github.com/Tommo-L/NEO3-Development-Guide#transactions

The free 10 GAS on transactions has been removed and the network fee calculation has been changed, another client change that shouldn't be too involved.

**Comment by spencercorwin** [comment]
Important for making sure transactions and claims go through

**Comment by spencercorwin** [comment]
See #2235
