### ISSUE TITLE
Delete Alternative Transaction Models

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#1881]
https://github.com/Tommo-L/NEO3-Development-Guide#transactions

Transactions have been fundamentally reworked beginning with the removal of all transaction types besides a singular `transaction` model. This will probably be the most involved changes of the 3.0 client migration and may warrant other issues in the future. For now the tasks needed to be complete are:

- [x] Remove every transaction except `InvocationTransaction` and rename to just `Transaction`.
- [x] Update the current `Transaction` model to match the model changes made in 3.0.
- [ ] discard the UTXO model for NEO and GAS and use the account model from the native contract. We have a lot of code involving inputs/outputs and calculating balances so this will be ~80% removal of old code.

**Comment by spencercorwin** [comment]
Covered by #2142 and #1975, etc.
