### ISSUE TITLE
[Rush] Publishing Format

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#1893]
### Description

right now we have 3 different releases per package for each format. Because of this we can't use the builtin rush publishing mechanisms and we have to use our old custom method. 

### Steps

1. Change the package `lib` format to use something like `dist/cjs`, `dist/esm`, `dist/browser`
2. Add a `release` flag to the `rush build` command that builds all 3 formats, while running `rush build` without this flag would just build `dist/cjs`.
3. Define `main`, `module`, and `browser` fields in each package.json that puts to the appropriate entry point in `dist`.
4. Add `.npmignore` files to every package to ignore extraneous developer files. (see [link](https://github.com/microsoft/rushstack/blob/master/apps/api-documenter/.npmignore))
5. Test dry-runs using `rush version` / `rush publish`

**Comment by spencercorwin** [comment]
Done. https://github.com/neo-one-suite/neo-one/pull/2034
