### ISSUE TITLE
Add ledger support

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#192]

**Comment by dicarlo2** [comment]
We can add a new [`KeyStore`](https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-client/src/user/LocalUserAccountProvider.ts#L80) implementation that supports ledger, say `LedgerKeyStore`. See [`LocalKeyStore`](https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-client/src/user/keystore/LocalKeyStore.ts) for an example of an implementation of the interface. Effectively what it should do is extract the available accounts (addresses) from the ledger device to populate the various account methods as well as locally store things like the account name and which accounts have been "deleted". It should implement `sign` using the Ledger api as well.

We'll want to target both the Ledger api for node and for the browser and the best way to do this in neo-one is to create a separate package with entrypoints for both node and the browser. The structure should look something like this:

- packages
    - neo-one-client-ledger-keystore
        - src
            - index.ts
            - index.browser.ts
            - LedgerNodeKeyStore.ts
            - LedgerBrowserKeyStore.ts
        - package.json
        - tsconfig.json
 
Where index.ts looks like
```typescript
export { LedgerNodeKeyStore as LedgerKeyStore } from './LedgerNodeKeyStore';
```

and index.browser.ts looks like

```typescript
export { LedgerBrowserKeyStore as LedgerKeyStore } from './LedgerBrowserKeyStore';
```

The ledger browser api can be seen in use [here](https://github.com/leeyikjiun/blue-app-neo-tests/blob/master/test/u2f.js). The ledger node api [here](https://github.com/leeyikjiun/blue-app-neo-tests/blob/master/test/node-hid.js). They're effectively the same, so you'll likely want to make a base class `LedgerKeyStore` that takes in which one of the apis to use. Then your `LedgerNodeKeyStore` and `LedgerBrowserKeyStore` just subclass `LedgerKeyStore` and call `super` with the appropriate api.

Use the Ledger from my desk to test. You should write unit tests just like normal, but put them under a different directory like `__tests_ledger__` so that they are not automatically run with all of the other tests. Then create a `test-ledger` script in the root `package.json` similar to the `e2e` script that runs your unit tests so that we can trigger them manually.

Also, be sure to write normal unit tests under `__test__` that test your base class with a mock ledger interface.

**Comment by danwbyrne** [comment]
https://github.com/LedgerHQ/ledgerjs

using @ledgerhq/hw-transport-node-hid for physical ledger API and @ledgerhq/hw-transport-uf2 for browser API. Started building an abstract class for both of them. Neither of the ledgerhq libraries have built d.ts files available so I will look into implementing my own or finding a workaround (TS is throwing a fit in the editor).
