### ISSUE TITLE
Neo-one build command fails after init

### ISSUE THREAD

**Issue by burakiskender** [neo-one-suite/neo-one#1948]
### Description
neo-one cli build command fails after neo-one init. Here is the command output

$ neo-one build
  ✔ Start development network
  ✖ Setup wallets
    → Relay transaction failed: Key 40xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b not found in database.:-110
    Deploy
    Generate common code
[1577946516017] ERROR:
    service: "cli"
    err: {
      "type": "Error",
      "message": "Relay transaction failed: Key 4\u00000xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b not found in database.:-110",
      "stack":
          Error [JSON_RPC]: Relay transaction failed: Key 40xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b not found in database.:-110
              at doRequest (/Users/burakiskender/Labs/neo-one/OneToken/node_modules/@neo-one/client-core/provider/JSONRPCHTTPProvider.ts:182:17)
              at process._tickCallback (internal/process/next_tick.js:68:7)
      "context": {
        "foundContracts": [],
        "deployed": {}
      }
    }

### Steps to Reproduce

1. create a new angular boiler plate with npx @angular/cli@next new MyProject
2. cd MyProject and execute neo-one init
3. execute neo-one build 

**Expected behavior:** [What you expect to happen]
It should complete all steps
**Actual behavior:** [What actually happens]
Fails at step 2
![Screen Shot 2020-01-03 at 8 50 26 am](https://user-images.githubusercontent.com/3093522/71695421-30b3e980-2e06-11ea-82e7-76c4de667762.png)

**Reproduces how often:** [What percentage of the time does it reproduce?]
100% Always 

### Versions
neo-one cli 1.3.3

**Comment by afragapane** [comment]
Hi!  Thanks for submitting this issue.  Currently @neo-one/cli is on version 2.4.0 https://www.npmjs.com/package/@neo-one/cli .  Can you try with the latest version and let us know if the problem persists?

**Comment by burakiskender** [comment]
Hi @afragapane , tried with 2.4.0 .  same error message": "Relay transaction failed: Key 4\u00000xc56f33fc6ecfcd0c225c4ab356fee59390af8560be0e930faebe74a6daff7c9b not found in database.:-110",   Setup Wallets step failing.

**Comment by afragapane** [comment]
Hi @burakiskender, did you try with the latest version of all packages in the @neo-one/suite 2.3.1 (https://www.npmjs.com/package/@neo-one/suite)?  This includes @neo-one/cli 2.4.0, @neo-one/client 2.3.0, @neo-one/smart-contract 2.3.0, @neo-one-smart-contract-test 2.3.1, @neo-one/smart-contract-lib 2.3.1, and @neo-one/smart-contract-typescript-plugin 2.3.0.  Sorry for not being more clear.  

In case you haven't already, also worth noting that the above packages must be installed for `neo-one build` to work properly.  In our tutorial we do `npm install @neo-one/suite` to install the above packages before running `neo-one init` (https://neo-one.io/tutorial).

I have tried your steps, adding `npm install @neo-one/suite` before `neo-one init` and using the above listed versions of @neo-one and did not encounter any issues.  I used node 10.16 and am on MacOS Mojave 10.14.5

**Comment by burakiskender** [comment]
@afragapane , tried with  npm install @neo-one/suite , exact same versions you specified, but no luck. It does fails at step2 setting up the wallets.[Screen Shot 2020-01-03 at 1 44 09 pm](https://user-images.githubusercontent.com/3093522/71704550-2bb76000-2e2f-11ea-9cce-c3f9f43fa06e.png) . Is there any other prerequisite or another way to set it up?

**Comment by danwbyrne** [comment]
I just tried this with
```
npx @angular/cli@next new MyProject
cd MyProject
yarn add @neo-one/cli
yarn add @neo-one/smart-contract-lib (should come with @neo-one/cli, will look into that)
yarn neo-one init
yarn neo-one build
```
and it started the network successfully.

Something you could try is clearing any old server files from `~/Library/Application Support/neo-one` and running `yarn neo-one reset --static-neo-one`.

If you are using npm these commands will be a bit different, but it should work the same, you can @ me if this doesn't help clear the issue.

**Comment by burakiskender** [comment]
@danwbyrne , thanks for that. There is no such folder ~/Library/Application Support/neo-one. I have executed the yarn commands instead of npm but same result
![Screen Shot 2020-01-05 at 7 20 04 pm](https://user-images.githubusercontent.com/3093522/71777185-79c79180-2ff0-11ea-8803-6d0df1db11f7.png)

**Comment by burakiskender** [comment]
Tried on a windows machine , now getting : "Network is not ready"
I am not doing anything different than the tutorials , also both machines are pretty new.
Thanks in advance.

![neo-one-build](https://user-images.githubusercontent.com/3093522/71778054-c9ac5580-2ffc-11ea-8cea-d291855c961d.png)

**Comment by danwbyrne** [comment]
Hi again @burakiskender 

at this point I'm really not sure what could be causing this issue, I've tried running the above commands on my mac, windows desktop, and inside of a docker image and haven't had any trouble. The only thing I can think of is some sort of mismatch in a package you have installed globally. Is there a way you could try setting up `@neo-one` in a fresh environment?

For reference the Dockerfile I tested with was as simple as:
```
FROM neotracker/neo-one-circleci-node@sha256:6f76ab22882896c057d9d805955892f1dee26bb1a4257a6d095d07d617aa4d5c as builder
RUN mkdir -p /tmp/neo-one
WORKDIR /tmp/neo-one

RUN yarn add @neo-one/suite
```

then 

```
docker build -t neo-one:test
docker run -it neo-one:test /bin/bash
```
