### ISSUE TITLE
delete command should prompt for confirmation

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#20]
### Description

`neo-one delete` (or aliases) should prompt to confirm.

### Steps to Reproduce

1. `create net neo`
2. `delete net neo`

**Expected behavior:** Prompts to confirm deletion

**Actual behavior:** Deletion happens immediately

**Reproduces how often:** 100%

### Versions

v0.0.1

### Additional Information

Code Pointers:
- Deletion command is defined [here](https://github.com/neo-one-suite/neo-one/blob/90e537ee7d1b49da0986a2b9054783a240eac50f/packages/neo-one-cli/src/interactive/createCRUD.js#L326)

**Comment by afragapane** [comment]
Taking a look at this

**Comment by dicarlo2** [comment]
Looks good. I'll probably open another issue later for prompting about the dependent resources that will be deleted.
