### ISSUE TITLE
Problems in TS contract execution

### ISSUE THREAD

**Issue by txhsl** [neo-one-suite/neo-one#2016]
### Description

I'm following the [tutorial](https://neo-one.io/tutorial) to build a TS project of NEO smart contract. And I met three problems in compiling and testing.

1. Can't get the first item in `ArrayStorage` with the index `0`. Here I passed `1` as id and used `this.array[id - 1]` to fetch the first item. The same error didn't occur when I passed `2` as id to fetch the second one. 
![index](https://user-images.githubusercontent.com/30062598/80463563-ff3dcb80-896a-11ea-8a7e-3360daba7a32.png)

2. The script after `switch` and `if...else` structures is not going to be executed. Here the first `console.log()` worked when the `attribute` was `0`, but the second one was not executed. I got a message `hello?` without `hello!`. And the same thing also happend when I tried an `if..else` structure.
![switch](https://user-images.githubusercontent.com/30062598/80464172-f994b580-896b-11ea-9268-df8c97eaf468.png)
Actually, I was trying to update the storage here, and the solution below worked.
![switch2](https://user-images.githubusercontent.com/30062598/80464180-fd283c80-896b-11ea-9401-166700235992.png)

3. The comparison between two `BigInteger` shows a wrong result. Here I was going to compare two `BigInteger`s which had the same value. But the result showed that they are different. The same thing happened when I used `==` instead of `!=` and `toBeFalsy()` instead of `toBeTruthy()`.
![test](https://user-images.githubusercontent.com/30062598/80464864-fc43da80-896c-11ea-97e8-3e518e7c8882.png)

I will attach both the contract file and test file in this issue. See the 'Additional Information'.

### Steps to Reproduce

1. Set up the development environment according to the [instruction](https://neo-one.io/tutorial#Setup).
2. Replace the contract file and test file.
3. Run `npx neo-one build` and `npm test`.

**Expected behavior:** 
1. Get the first item in `ArrayStorage`.
2. The script after `switch` and `if...else` structures is executed.
3. The comparison shows `63925180` and `63925180` have the same value.

**Actual behavior:** 
1. Error message.
2. The script after `switch` and `if...else` structures is not executed, or sometimes just times out.
3. The comparison shows `63925180` and `63925180` are different.

**Reproduces how often:** Always.

### Versions

> linux@ubuntu:~/Desktop/neo-one/token$ npm view
> 
> token@0.1.0 | BSD-3-Clause | deps: none | versions: 2
> HMAC token generation and verification with time-based limitation on validity
> https://github.com/mixu/token#readme
> 
> keywords: authentication, auth, access, token, hmac, hash, time
> 
> dist
> .tarball: https://registry.npmjs.org/token/-/token-0.1.0.tgz
> .shasum: b2d96487582f0d9da231c361adac36b5a26c73c2
> 
> maintainers:
> - mixu <mixu@mixu.net>
> 
> dist-tags:
> latest: 0.1.0 
> 
> published over a year ago by mixu <mixu@mixu.net>

It works on `Ubuntu 18.04.1 LTS` and `npm@6.13.4`

### Additional Information

- The contract file is [here](https://github.com/alienworks/InteractiveTutorial-Lessons/blob/ef4ac98c18f8b8f09ce375b403301ee7b93a86fa/Typescript/en-us/Lesson02/AlienFinder.ts) and the test file are [here](https://github.com/alienworks/InteractiveTutorial-Lessons/blob/ef4ac98c18f8b8f09ce375b403301ee7b93a86fa/Typescript/en-us/Lesson02/AlienFinder.test.ts).
- Find the test code for function `mutate` [here](https://github.com/alienworks/InteractiveTutorial-Lessons/blob/master/Typescript/en-us/Lesson02/AlienFinder.test.ts#L38).
- The contract and test which can run correctly(using a map) are [here](https://github.com/alienworks/InteractiveTutorial-Lessons/tree/06c5a3e5bac21e69ff22a12142292a44c4ccefd1/Typescript/en-us/Lesson02).

**Comment by danwbyrne** [comment]
Heya @txhsl I'm taking a look at the first 2 problems you are facing and I'll get back to you I have your project loaded up and I'm testing locally. However for the third issue involving BigNumber comparisons you just need to use the `isEqualTo` property of a BigNumber i.e
```
expect(mutatedAlien.xna.isEqualTo(someAlien.xna)).toBeTruthy();
```

**Comment by txhsl** [comment]
> Hi @txhsl. Thank you for bringing this to our attention. We can take a look at this today or in the next few days. What version of @neo-one are you using?

@spencercorwin  I think it's `@neo-one/suite@2.3.1`, while the related dependencies look like,
>     "@neo-one/cli": "^2.4.0",
>     "@neo-one/client": "^2.3.0",
>     "@neo-one/smart-contract": "^2.3.0",
>     "@neo-one/smart-contract-lib": "^2.3.1",
>     "@neo-one/smart-contract-test": "^2.3.1",
>     "@neo-one/smart-contract-typescript-plugin": "^2.3.0"

> Heya @txhsl I'm taking a look at the first 2 problems you are facing and I'll get back to you I have your project loaded up and I'm testing locally. However for the third issue involving BigNumber comparisons you just need to use the isEqualTo property of a BigNumber i.e
> expect(mutatedAlien.xna.isEqualTo(someAlien.xna)).toBeTruthy();

@danwbyrne That's very helpful, thanks.

**Comment by spencercorwin** [comment]
Unfortunately this bug looks a bit harder to solve than I originally thought it would be. I focused entirely on the `ArrayStorage` lookup issue. Here are my notes:

### The best way to reproduce this error in our own unit test:
- Change `assertEqual(storage[0], '10')` to `assertEqual(storage[2 - 2], '10')` [here](https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/arrayStorage.test.ts#L19)
- Then run `rush test -t packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/arrayStorage.test.ts`
- See that the first unit test fails with the error: `Invalid PICKITEM Index: 1. Value ["01"]`
- I think this is the best way to test similar behavior and to test changes in the compiler that you might think will fix the bug.

### Something important to note:
- If you set a value in the `ArrayStorage` with `[2 - 2]` and do a storage lookup with `[2 - 2]`, then that will work.
- For example if you modify lines 18-23 in that same unit test to this, the tests will pass:
```
        storage[0] = '10';
        storage[2 - 2] = 'spencer is cool';
        assertEqual(storage.length, 1);
        assertEqual(storage[2 - 2], 'spencer is cool');
        assertEqual(storage[0], '10');
```
- Even though you should have set a value at index `0` twice, it compiles that to two different index values.

### Potential workarounds for now:
- I tried to find a workaround, like by storing the computed index value in an intermediate variable and then using that as the lookup value. But nothing worked
- The best I could come up with was to do something like this:
```
        const getLookup = (id: number): number => {
          switch(id) {
            case 0:
              return -1;
            case 1:
              return 0;
            case 2:
              return 1;
            default:
              return 0;
          }
        }
        
        storage[getLookup(id)]
```
- Note that the `getLookup` needs to return a hard-coded number and not a computed one.
- Maybe the information in the second section can help you come up with a clever workaround.

### Where I think we should focus in the compiler code:
- `ArrayStorage` is considered a type of `StructuredStorage` in the compiler.
- I'm fairly certain that the helper which sets values for `ArrayStorage` is the `SetStructuredStorageHelper.ts`. ie `storage[0] = '10'`.
- I think that the storage access is handled by `ElementAccessExpressionCompiler.ts`.

**Comment by txhsl** [comment]
@spencercorwin How about the second problem?

**Comment by spencercorwin** [comment]
Hi @txhsl. I haven't had a chance to look at the switch statement problem. These compiler issues are high on my list of things to do, but I currently have a few critical issues I must get done first. Since you were able to get around the switch-statement issue I didn't look at it. If you want to take a look at the problem yourself I think I can point you in the right direction.

**Comment by txhsl** [comment]
@spencercorwin It doesn't matter. I'm glad that you invited me to look through this problem, but I'm not familiar with TypeScript and the compiler indeed.

**Comment by spencercorwin** [comment]
Sounds good @txhsl. I'll try to keep you updated on our progress with this.

**Comment by spencercorwin** [comment]
Possibly more information here: https://github.com/neo-one-suite/neo-one/issues/1392

**Comment by spencercorwin** [comment]
Hi @txhsl. You said above that for the switch statement problem you couldn't get it to work with `if/else` statements either, correct? I haven't been able to recreate the same issue using `if/else` statements. Could you comment here exactly what you tried with `if/else` statements? I think it will help me fix the `switch` statement issue.

**Comment by txhsl** [comment]
@spencercorwin I'm not sure. I remember I tried to avoid the `switch` problem by replacing it with some `if/else` statements but failed as well. It contains many `else if` keywords, but I cannot reproduce it for you now.

**Comment by spencercorwin** [comment]
Ok. Thank you @txhsl. I'm working on this now.
