### ISSUE TITLE
Finish unimplemented NEODataProvider methods

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#2019]
# Description
The NEODataProvider is the DataProvider used in the client when running an official C# node.  All the methods required to run neotracker have been implemented, but there are still a few left unimplemented in neo-one.  These should be implemented so that all neo-one Client features can be used with a C# node.

The Neo RPC calls we have to work with on the 2.x branch are here: https://github.com/neo-project/neo/blob/master-2.x/neo/Network/RPC/RpcServer.cs

Additional Neo RPC calls are available through 2.x plugins here: https://github.com/neo-project/neo-modules/tree/master-2.x

### Methods that need to be implemented:
`getInvocationData`: This method is very high priority.  This method has quite a few uses in neo-one.  In particular it is needed when confirming an invocation transaction via `result.confirmed()`.  The neo-one node has this as a custom rpc method, but Neo does not provide anything comparable.  

`iterStorage`:  This method is medium-high priority.  The neo-one node has an rpc call `getallstorage` which returns all storage for a given contract.  This is used to iterate over all of a single contract's storage.  The Neo node instead has `getstorage` which only returns the storage item for a specific storage key instead of for the whole contract.  So one option may be to somehow construct all the keys for a contract and iterate over them.

`iterActionsRaw`: This method is medium priority.  iterActionsRaw is used by the `UserAccountProviderBase` & `LocalUserAccountProvider`.  In both instances, however, it is not actually required.  Could instead leave this method undefined on the `NEOProvider`.

`getNetworkSettings`:  This method is low priority. This method returns the network settings of a neo-one node.  Probably makes sense to leave this unimplemented since it only returns a single setting that is not relevant for the neo node.  

`getClaimAmount`: This method is low priority.  It is not used higher up in the Client.  Could probably be deprecated.

### Methods with flaws:
`testInvoke`: 
- The Neo node does not return the array of `actions` on a test invocation using the `invokescript` RPC call.   Currently that is set to an empty array, but it would be great if there was a way to actually get the actions.  
- The Neo node does not return an error message on a test invocation using the `invokescript` RPC call.  Currently the `message` is set to an empty string, but it would be great if there was a way to get the actual error message. 
- Note that for this method to work on a Neo node without the transaction option `{skipSysFeeCheck: true}`, the node will need to compiled using the current Neo code.  These changes allow `CheckWitness` syscalls to be performed in test invocations without failure: https://github.com/neo-project/neo/blob/75df7cdaeffc84cd116d907ceda11054be696af3/neo/Network/RPC/RpcServer.cs#L281 , but are not included in the current 2.10.3 release.

`getTransactionReceipt`: The `globalIndex` of a transaction is not returned from a Neo node.  I have this set to default to -1.  It would be nice if there was a way to get the actual value, but I don't think there will be without modifying Neo itself.  

`relayTransaction`: Currently this only supports `Invocation` and `Claim` transactions.  These are the only kinds of transactions that the neo-one Client technically needs to support, so it should be fine to leave it - especially since the other types are irrelevant as we head towards 3.0.

**Comment by spencercorwin** [comment]
There's a failing test in `packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/blockchain.test.ts` which I believe is related to the uncompleted implementation of `testInvoke` in the `DataProvider`s.

**Comment by spencercorwin** [comment]
See https://github.com/neo-one-suite/neo-one/issues/2055
