### ISSUE TITLE
Add DeveloperProvider methods to NEODataProvider

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#2020]
### Description
The DeveloperProvider methods allow a neo-one DeveloperClient to have great control over a private network.  This is required for testing neo-one smart contracts using the code generated with `neo-one build`.  For a C# Neo node to be an option in neo-one, these will need to be implemented as RPC call handlers in the node itself.  This will probably mean writing a custom plugin for the Neo node.  The RPC plugins are here:
2.x: https://github.com/neo-project/neo-modules/tree/master-2.x
3.0: https://github.com/neo-project/neo-modules/tree/master/src

In particular `runConensusNow` is the most crucial as it is called each time a transaction is performed in unit tests.

**Comment by spencercorwin** [comment]
See https://github.com/neo-one-suite/neo-one/issues/2055
