### ISSUE TITLE
Unknown compilation error

### ISSUE THREAD

**Issue by txhsl** [neo-one-suite/neo-one#2029]
### Description

When I was trying to compile a smart contract by typing `npx neo-one build`, the compilation failed without a clear error message.

![unknown error](https://user-images.githubusercontent.com/30062598/81176116-406f5480-8fd7-11ea-9ec0-9da600d97e9c.png)

The full output in cmd was,

>     linux@ubuntu:~/Desktop/neo-one/token$ npx neo-one build
> 
>     ✔ Start development network
>     ✔ Setup wallets
>     ❯ Deploy
>     ✖ Deploy AlienFinder
>       →       271 |                 notifyEvent('speed', id);
>     Generate common code
>     Start NEO tracker instance
>     [1588682538999] ERROR:
>     service: "cli"
>     err: {
>       "type": "Error",
>       "message": "Compilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (256,5): Compilation failed for an unknown error, please report\n\n    \u001b[0m \u001b[90m 254 | \u001b[39m    }\u001b[0m\n    \u001b[0m \u001b[90m 255 | \u001b[39m\u001b[0m\n    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 256 | \u001b[39m    public forward(id\u001b[33m:\u001b[39m number) {\u001b[0m\n    \u001b[0m \u001b[90m     | \u001b[39m    \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 257 | \u001b[39m        let alien\u001b[33m:\u001b[39m \u001b[33mAlien\u001b[39m \u001b[33m=\u001b[39m \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39mquery(id)\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 258 | \u001b[39m        let event\u001b[33m:\u001b[39m number \u001b[33m=\u001b[39m \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39md6()\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 259 | \u001b[39m\u001b[0m\n\nCompilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (88,5): Compilation failed for an unknown error, please report\n\n    \u001b[0m \u001b[90m 86 | \u001b[39m    }\u001b[0m\n    \u001b[0m \u001b[90m 87 | \u001b[39m\u001b[0m\n    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 88 | \u001b[39m    \u001b[33m@\u001b[39mconstant\u001b[0m\n    \u001b[0m \u001b[90m    | \u001b[39m    \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 89 | \u001b[39m    public query(id\u001b[33m:\u001b[39m number)\u001b[33m:\u001b[39m \u001b[33mAlien\u001b[39m {\u001b[0m\n    \u001b[0m \u001b[90m 90 | \u001b[39m        \u001b[36mconst\u001b[39m alien \u001b[33m=\u001b[39m \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39maliens\u001b[33m.\u001b[39mget(id)\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 91 | \u001b[39m        \u001b[36mif\u001b[39m (alien \u001b[33m===\u001b[39m undefined) {\u001b[0m\n\nCompilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (258,29): Compilation failed for an unknown error, please report\n\n    \u001b[0m \u001b[90m 256 | \u001b[39m    public forward(id\u001b[33m:\u001b[39m number) {\u001b[0m\n    \u001b[0m \u001b[90m 257 | \u001b[39m        let alien\u001b[33m:\u001b[39m \u001b[33mAlien\u001b[39m \u001b[33m=\u001b[39m \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39mquery(id)\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 258 | \u001b[39m        let event\u001b[33m:\u001b[39m number \u001b[33m=\u001b[39m \u001b[36mthis\u001b[39m\u001b[33m.\u001b[39md6()\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m     | \u001b[39m                            \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 259 | \u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 260 | \u001b[39m        \u001b[36mswitch\u001b[39m(event) {\u001b[0m\n    \u001b[0m \u001b[90m 261 | \u001b[39m            \u001b[36mcase\u001b[39m \u001b[35m0\u001b[39m\u001b[33m:\u001b[39m {\u001b[0m\n\nCompilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (261,21): Compilation failed for an unknown error, please report\n\n    \u001b[0m \u001b[90m 259 | \u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 260 | \u001b[39m        \u001b[36mswitch\u001b[39m(event) {\u001b[0m\n    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 261 | \u001b[39m            \u001b[36mcase\u001b[39m \u001b[35m0\u001b[39m\u001b[33m:\u001b[39m {\u001b[0m\n    \u001b[0m \u001b[90m     | \u001b[39m                    \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 262 | \u001b[39m                \u001b[90m// strength event(digits 3-4), remove some obstacle in the way\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 263 | \u001b[39m                let strength\u001b[33m:\u001b[39m number \u001b[33m=\u001b[39m alien\u001b[33m.\u001b[39mxna \u001b[33m%\u001b[39m \u001b[35m1E6\u001b[39m \u001b[33m/\u001b[39m \u001b[35m1E4\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 264 | \u001b[39m                notifyEvent(\u001b[32m'strength'\u001b[39m\u001b[33m,\u001b[39m id)\u001b[33m;\u001b[39m\u001b[0m\n\nCompilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (268,21): Compilation failed for an unknown error, please report\n\n    \u001b[0m \u001b[90m 266 | \u001b[39m                \u001b[36mbreak\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 267 | \u001b[39m            }\u001b[0m\n    \u001b[0m\u001b[31m\u001b[1m>\u001b[22m\u001b[39m\u001b[90m 268 | \u001b[39m            \u001b[36mcase\u001b[39m \u001b[35m1\u001b[39m\u001b[33m:\u001b[39m {\u001b[0m\n    \u001b[0m \u001b[90m     | \u001b[39m                    \u001b[31m\u001b[1m^\u001b[22m\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 269 | \u001b[39m                \u001b[90m// speed event(digits 5-6), run through dangerous area\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 270 | \u001b[39m                let speed\u001b[33m:\u001b[39m number \u001b[33m=\u001b[39m alien\u001b[33m.\u001b[39mxna \u001b[33m%\u001b[39m \u001b[35m1E4\u001b[39m \u001b[33m/\u001b[39m \u001b[35m1E2\u001b[39m\u001b[33m;\u001b[39m\u001b[0m\n    \u001b[0m \u001b[90m 271 | \u001b[39m                notifyEvent(\u001b[32m'speed'\u001b[39m\u001b[33m,\u001b[39m id)\u001b[33m;\u001b[39m\u001b[0m\n",
>       "stack":
>           Error: Compilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (256,5): Compilation failed for an unknown error, please report
>           
>                 254 |     }
>                 255 | 
>               > 256 |     public forward(id: number) {
>                     |     ^
>                 257 |         let alien: Alien = this.query(id);
>                 258 |         let event: number = this.d6();
>                 259 | 
>           
>           Compilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (88,5): Compilation failed for an unknown error, please report
>           
>                 86 |     }
>                 87 | 
>               > 88 |     @constant
>                    |     ^
>                 89 |     public query(id: number): Alien {
>                 90 |         const alien = this.aliens.get(id);
>                 91 |         if (alien === undefined) {
>           
>           Compilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (258,29): Compilation failed for an unknown error, please report
>           
>                 256 |     public forward(id: number) {
>                 257 |         let alien: Alien = this.query(id);
>               > 258 |         let event: number = this.d6();
>                     |                             ^
>                 259 | 
>                 260 |         switch(event) {
>                 261 |             case 0: {
>           
>           Compilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (261,21): Compilation failed for an unknown error, please report
>           
>                 259 | 
>                 260 |         switch(event) {
>               > 261 |             case 0: {
>                     |                     ^
>                 262 |                 // strength event(digits 3-4), remove some obstacle in the way
>                 263 |                 let strength: number = alien.xna % 1E6 / 1E4;
>                 264 |                 notifyEvent('strength', id);
>           
>           Compilation error: /home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts (268,21): Compilation failed for an unknown error, please report
>           
>                 266 |                 break;
>                 267 |             }
>               > 268 |             case 1: {
>                     |                     ^
>                 269 |                 // speed event(digits 5-6), run through dangerous area
>                 270 |                 let speed: number = alien.xna % 1E4 / 1E2;
>                 271 |                 notifyEvent('speed', id);
>           
>               at Object.throwOnDiagnosticErrorOrWarning (/home/linux/Desktop/neo-one/token/node_modules/@neo-one/smart-contract-compiler/utils/throwOnDiagnosticErrorOrWarning.ts:17:11)
>               at Object.exports.compileContract (/home/linux/Desktop/neo-one/token/node_modules/@neo-one/smart-contract-compiler/api.ts:23:3)
>               at Object.exports.deployContract (/home/linux/Desktop/neo-one/token/node_modules/@neo-one/cli/build/deployContract.ts:16:20)
>               at Task.task (/home/linux/Desktop/neo-one/token/node_modules/@neo-one/cli/build/createTasks.ts:48:77)
>               at /home/linux/Desktop/neo-one/token/node_modules/listr/lib/task.js:167:30
>               at processTicksAndRejections (internal/process/task_queues.js:97:5)
>       "context": {
>         "foundContracts": [
>           {
>             "filePath": "/home/linux/Desktop/neo-one/token/neo-one/contracts/AlienFinder.ts",
>             "name": "AlienFinder",
>             "dependencies": []
>           }
>         ],
>         "deployed": {},
>         "linked": {},
>         "sourceMaps": {},
>         "contracts": []
>       }
>     }
> 

### Steps to Reproduce

1. Get the smart contract [here](https://github.com/txhsl/InteractiveTutorial-Lessons/blob/master/Typescript/en-us/Lesson04/AlienFinder-NEP11.ts).
2. Type `npx neo-one build` in cmd to trigger a compilation.

**Expected behavior:** Get compiled successfully or a distinct error message

**Actual behavior:** Get the message `Compilation failed for an unknown error, please report`

**Reproduces how often:** Always

### Versions

`@neo-one/suite@2.3.1`, with these related dependencies,

>     "@neo-one/cli": "^2.4.0",
>     "@neo-one/client": "^2.3.0",
>     "@neo-one/smart-contract": "^2.3.0",
>     "@neo-one/smart-contract-lib": "^2.3.1",
>     "@neo-one/smart-contract-test": "^2.3.1",
>     "@neo-one/smart-contract-typescript-plugin": "^2.3.0"

**Comment by spencercorwin** [comment]
Hi @txhsl. Thank you for submitting this issue. I'll try to take a look at this later today.

**Comment by spencercorwin** [comment]
It turns out that this is actually a *very* difficult problem to solve. Essentially the compiled contract is too big. I tried to play around with the code to get it to compile but the problem with this particular example is that the entire contract's bytecode is too large to resolve jumps within the 15 bit limit number limit of the Neo VM. I'm still working on a solution but it may be something that will have to wait until we upgrade to Neo3. The Neo3 VM may have a more efficient instruction set, which would decrease the bytecode size of any given contract. So stay tuned.

**Comment by txhsl** [comment]
@spencercorwin Good luck!

**Comment by spencercorwin** [comment]
It turns out that this issue is not solvable in the way I was going about it. We need to optimize our compiler to emit less bytecode. Even if we were able to solve the jump instruction issue there is still a hard limit on Neo contract bytecode size. We need to create another step to optimize bytecode on a low-level. To work around this for now you could split this contract into two contracts that call each other. For example there could be one contract for game state and one contract for game actions. So for now I'm going to close this issue since this issue is covered by #2001
