### ISSUE TITLE
Investigate/fix/update @neo-one/suite

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#2097]
As good as an idea as it was it actually doesn't really work in practice. When I tried to use it on deployment example repos using `@neo-one/suite` stopped automatic imports from working when you would expect it to. We should delete it and stop referring to it in the documentation just install the neo-one packages you are going to use.

**Comment by spencercorwin** [comment]
Automatic imports don't work. Investigate how we can get this to work with VSCode with `@neo-one/suite`.
