### ISSUE TITLE
Add fork update to master-2.x branch

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#2168]
See the 2.12-update branch. 

For now we are just going to swap the setting out for our live nodes but it would be helpful to do the same thing with `maxTransactionsPerBlock` that I did with `getFreeGas`.

**Comment by spencercorwin** [comment]
See here: https://github.com/neo-one-suite/neo-one/commit/50aa1f2387b4aac46fe4dc4b54ae70e081d95aa9
