### ISSUE TITLE
Rewire `Notification` type on client side

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#2191]
After the migration to 3.0 the `NotificationRaw` & `NotificationJSON` types in `@neo-one/client-common` are not what they used to be / need to be reformed.

**Comment by spencercorwin** [comment]
Also look at `notificationToJSON` function in `neo-one-node-core/src/utils/notificationToJSON.ts`

**Comment by spencercorwin** [comment]
Duplicated in #2218
