### ISSUE TITLE
Finish mempool / consensus implementations in @neo-one/node-protocol

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#2192]
title.

`node-protocol` is finished except for the `trimMemPool` functionality that will be finished with the upcoming consensus work.

**Comment by spencercorwin** [comment]
Needs to also split out verified and unverified transactions in the mempool to match a change they made to 2.x version in March of 2019

**Comment by spencercorwin** [comment]
Should be done with #2222 and #2235
