### ISSUE TITLE
Investigate `executeInvokeMethod` and `executeInvokeScript` in `LocalUserAccountProvider.ts`

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#2206]
afaik these can become the `invokeScript` and `invokeFunction` from the neo-modules code, but we should double check we didn't set it up this way for some edge case in particular.

see #2098 for follow up / more thoughts on how the client models might need to change.

**Comment by spencercorwin** [comment]
Duplicated in #2218
