### ISSUE TITLE
Add a Client method for consolidating outputs

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#221]
Ledger has a maximum transaction size that it can support, which means that if an address has a large number of small outputs it may be impossible to construct a single transaction within that limit. Let's add a method to the [`Client`](https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-client/src/Client.ts#L34) with the following signature:

```
public consolidate(asset: Hash256String, maxInputs: number, options?: TransactionOptions): Promise<TransactionResult<TransactionReceipt>>;
```

that will create a contract transaction (similar to transfer) that will consolidate the smallest `maxInputs` inputs into a single output to the same address.

**Comment by danwbyrne** [comment]
After talking about this problem with Frag, and just so I'm clear on how this should be executed I think the plan of attack here is to use the UserAccount address to get the unspent input/outputs for that address, and then consolidate those outputs through some process.
