### ISSUE TITLE
Shell windows created for each node on Windows

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#24]
### Description

Title.

### Steps to Reproduce

1. start the cli on windows using cygwin
2. run command: create net wintest
3. observe shell windows created for each node (node.exe)

**Expected behavior:**  Creating a node should not create a window

**Actual behavior:** Creating a node creates a window

**Reproduces how often:** Every time

### Versions
v0.0.1

**Comment by afragapane** [comment]
Fixed by allowing Nodes to run as detached.

**Comment by dicarlo2** [comment]
#34
