### ISSUE TITLE
ctrl+C does not exit the CLI properly on Windows

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#26]
### Description

Title.

### Steps to Reproduce

1. Run the neo-one interactive CLI on Windows/cygwin
2. Press ctrl+C
3. Observe lack of exit/cleanup messages

**Expected behavior:** In the case where a command is being typed, the command is cleared.  In the case where the CLI is empty,  cleanup/exit processes are run and exit messages are displayed.

**Actual behavior:**  CLI completely exits without any cleanup or exit messages in all cases.

**Reproduces how often:** Every time.

### Versions
v0.0.1

**Comment by danwbyrne** [comment]
probably an issue with yarn as another interaction that doesn't work is:
`yarn build` -> `ctrl+c` to interrupt the build -> `yarn build`

on Windows, this leaves a hanging `nodejs` process that prevents that build from completing.
on OSX you can `ctrl+c` a `yarn build` all day and still have the final one go through.

**Comment by dicarlo2** [comment]
Going to archive this since we don't really use the interactive cli anymore. In fact, we should probably just remove the interactive cli and get rid of those dependencies...
