### ISSUE TITLE
Add support for mnemonic phrase keystore

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#292]
Some interesting reads from Bitcoin Improvement Propositions:

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

BIP32 seems extensive so I have quite a bit of reading to do there but it seems related?
BIP39 is details about mnemonic implementations with some additional libraries.

https://github.com/trezor/python-mnemonic here is an actual implementation of it in python.

**Comment by danwbyrne** [comment]
Some interesting reads from Bitcoin Improvement Propositions:

https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

BIP32 seems extensive so I have quite a bit of reading to do there but it seems related?
BIP39 is details about mnemonic implementations with some additional libraries.

**Comment by danwbyrne** [comment]
Add `addAccount` to the keystore and to localUserAccountProvider similar to how `updateAccountName` is implemented now.
