### ISSUE TITLE
Duplicate line printed for every command on Windows/cygwin

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#33]
Title.

### Steps to Reproduce

1. Run the neo-one interactive CLI on Windows/cygwin
2. Type any command - e.g. create net altest
3. Observe result:
neo-one$ create net altest
neo-one$ create net altest
  √ Create network altest
  √ Execute final setup
  √ Start network altest
  √ Execute plugin hooks

**Expected behavior:** No duplicate line should be printed
**Actual behavior:** A duplicate line is printed

**Reproduces how often:** Every time.

### Versions
v0.0.1

### Additional Information
Found on Windows 10 + cygwin

**Comment by danwbyrne** [comment]
![windows-dup.PNG](https://zube.io/files/neo-one/6a6e69b561bf558e3c4cdae2dd3a1e8f-windows-dup.png)
