### ISSUE TITLE
Ledger 2.0

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#415]
While we are at a solid base for ledger support, there is a few more things I would like to do in the future:
1) hook up the node-transport's `listen` function so we can plug-and-play with ledgers.
2) emulate a `listen` function for u2f-transport.
3) move scanning/updating into the ledger handler itself. I haven't really fleshed out this idea but I think it would be nice to scan on the fly instead of all at once when we `.init()`.
4) we could cache `account#` -> `publicKey` on each ledger if we are going to be scanning on the fly.
5) allow configurable names.

these are just ideas I've had, none are super fleshed out atm.

**Comment by dicarlo2** [comment]
@danwbyrne can you split this issue out into separate cards? Going to archive for now.
