### ISSUE TITLE
Add argument checking assertions to @neo-one/client Client

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#43]
### Description

Validate all arguments provided to Client methods.

**Comment by dicarlo2** [comment]
E.g. https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-client/src/Client.js#L65

**Comment by danwbyrne** [comment]
Your link from Feb 10th is no longer valid. If this is a priority card let me know. I've currently got multiple inputs & consolidating inputs as my priority.

**Comment by danwbyrne** [comment]
https://github.com/danwbyrne/neo-one/tree/client-arg-checking

Possible bug on an already defined method "assertBuffer".

when checking with: 
```typescript
if (Buffer.from(value, 'hex').toString('hex') ...
```
a character will be chopped off of odd-length hex strings.

I have at least one test per new assert method right now and all are passing. More to be done though.
