### ISSUE TITLE
Use 'ora' instead of 'elegant-spinner'

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#666]
https://github.com/sindresorhus/ora

same author, he links to this repo now from elegant-spinner and says its prefered. Might need to type it, will look into later.

**Comment by dicarlo2** [comment]
https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-server-plugin/src/handleCLITaskList.ts#L4 is the only spot where it's used

**Comment by dicarlo2** [comment]
@spencercorwin @danwbyrne is this done?

**Comment by spencercorwin** [comment]
To my knowledge, yes

**Comment by dicarlo2** [comment]
great, thanks!
