### ISSUE TITLE
E2E tests for JavaScript codegen

### ISSUE THREAD

**Issue by dicarlo2** [neo-one-suite/neo-one#717]
https://github.com/neo-one-suite/neo-one/blob/master/packages/neo-one-server-plugin-project/src/__e2e__/buildCommand.test.ts tests the project + codegen functionality e2e for TypeScript codegen. We should abstract this to also allow testing the JavaScript codegen.

**Comment by davemneo** [comment]
start with ```yarn build:e2e```

**Comment by davemneo** [comment]
copy the __data__/ico folder
and set it up for javascript
