### ISSUE TITLE
Prism.js for api example highlighting

### ISSUE THREAD

**Issue by afragapane** [neo-one-suite/neo-one#748]
Currently, we are highlighting word by word and using a package "html-to-react" to convert the highlighted code into react.  

We would like to remove the extra dependency and only use Prism.js.  The issue is that Prism.js by default removes links when highlighting an element.  Might be possible to use hooks to override this behavior.  
https://github.com/PrismJS/prism/issues/651

**Comment by spencercorwin** [comment]
Is the objective to simply make links within the code examples clickable? There's a Prism [autolinker](https://prismjs.com/plugins/autolinker/) plugin that accomplishes this. The autolinker examples are run without using the html-to-react package. Let me know if I'm on the right track and I can submit a PR for this shortly.

As an example, here's how a link looks on the website now:
![website now](https://user-images.githubusercontent.com/29364457/56461585-39dd5300-636a-11e9-90b4-bee2d38fd0a6.png)

Here's how the website looks on my machine without changes after running `yarn website:start-static`:
![static build normal](https://user-images.githubusercontent.com/29364457/56461593-5083aa00-636a-11e9-8c6b-04e36bac8baa.png)

Here's how it looks with the autolinker plugin:
![static build fixed](https://user-images.githubusercontent.com/29364457/56461596-5da09900-636a-11e9-84f7-aae414fc4192.png)

And here it is on hover:
![static build fixed hover](https://user-images.githubusercontent.com/29364457/56461600-64c7a700-636a-11e9-9cfc-83558492c6d8.png)

**Comment by dicarlo2** [comment]
@afragapane
