### ISSUE TITLE
Investigate tests hitting the 2000/minute request limit

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#750]
As of [neo-one-suite/neo-one#709 (neo-one-suite/neo-one#703)](https://zube.io/neo-one/neo-one/c/709) the new `rateLimit` middleware e2e tests `bootstrap20Wallets` fails because it hits the rateLimit. Increased it for now until this is resolved.

**Comment by davemneo** [comment]
Is this the failing test? 

![image.png](https://zube.io/files/neo-one/ab14c9f316d2d39d11d2c890002e45e5-image.png)
