### ISSUE TITLE
Investigate tests causing 1000ms+ lag and triggering the new `tooBusy` middleware

### ISSUE THREAD

**Issue by danwbyrne** [neo-one-suite/neo-one#751]
as of [neo-one-suite/neo-one#710 (neo-one-suite/neo-one#704)](https://zube.io/neo-one/neo-one/c/710) multiple tests fail the default 70ms tolerance, however a lot of them cause a suspicious amount of lag (over 1000ms). Need to resolve. Temporarily upped test default to 1000ms.

**Comment by davemneo** [comment]
What are the reproduction steps?

**Comment by dicarlo2** [comment]
TODO: Test with prod infra + https://artillery.io/
