### ISSUE TITLE
Fix errors asserted by ix-esnext-esm 2.4.3

### ISSUE THREAD

**Issue by davemneo** [neo-one-suite/neo-one#923]
### Description
updating ix-esnext-esm to 2.4.3 produced a collection of breaking errors.  See the PR for reverting to 2.3.5 (https://github.com/neo-one-suite/neo-one/pull/922).  Successful completion of this issue would include modifications to the source that fix these issues. 

And the removal of the forced resolution in the root `package.json` for this package.  

### Steps to Reproduce

    yarn install
    yarn build

**Expected behavior:** successful build

**Actual behavior:** collection of errors

**Reproduces how often:** every time

**Comment by dicarlo2** [comment]
@davemneo @danwbyrne is this still relevant?

**Comment by danwbyrne** [comment]
>@danwbyrne is this still relevant?

no
